D:/MLOps/dataset/
[2021-10-23 01:10:59,552][tensorflow][INFO] - Load image with size: 7553, num_label: 2, labels: with_mask, without_mask.
[2021-10-23 01:10:59,567][tensorflow][INFO] - Retraining the models...
[2021-10-23 01:10:59,569][absl][INFO] - Using C:\Users\phant\AppData\Local\Temp\tfhub_modules to cache modules.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
hub_keras_layer_v1v2 (HubKer (None, 1280)              2257984
_________________________________________________________________
dropout (Dropout)            (None, 1280)              0
_________________________________________________________________
dense (Dense)                (None, 2)                 2562
=================================================================
Total params: 2,260,546
Trainable params: 2,562
Non-trainable params: 2,257,984
_________________________________________________________________
None
Epoch 1/10
C:\Users\phant\.virtualenvs\MLOps-he8T28m9\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(










188/188 [==============================] - 31s 136ms/step - loss: 0.2781 - accuracy: 0.9739 - val_loss: 0.2271 - val_accuracy: 0.9932
Epoch 2/10








188/188 [==============================] - 22s 118ms/step - loss: 0.2395 - accuracy: 0.9902 - val_loss: 0.2245 - val_accuracy: 0.9932
Epoch 3/10








188/188 [==============================] - 21s 113ms/step - loss: 0.2322 - accuracy: 0.9929 - val_loss: 0.2240 - val_accuracy: 0.9959
Epoch 4/10








188/188 [==============================] - 21s 113ms/step - loss: 0.2278 - accuracy: 0.9942 - val_loss: 0.2183 - val_accuracy: 0.9973
Epoch 5/10








188/188 [==============================] - 21s 113ms/step - loss: 0.2260 - accuracy: 0.9947 - val_loss: 0.2168 - val_accuracy: 0.9973
Epoch 6/10








188/188 [==============================] - 21s 112ms/step - loss: 0.2253 - accuracy: 0.9953 - val_loss: 0.2169 - val_accuracy: 1.0000
Epoch 7/10








188/188 [==============================] - 21s 113ms/step - loss: 0.2244 - accuracy: 0.9960 - val_loss: 0.2159 - val_accuracy: 0.9973
Epoch 8/10








188/188 [==============================] - 21s 111ms/step - loss: 0.2245 - accuracy: 0.9963 - val_loss: 0.2159 - val_accuracy: 0.9973
Epoch 9/10








188/188 [==============================] - 21s 112ms/step - loss: 0.2229 - accuracy: 0.9967 - val_loss: 0.2160 - val_accuracy: 1.0000
Epoch 10/10









188/188 [==============================] - 21s 114ms/step - loss: 0.2216 - accuracy: 0.9973 - val_loss: 0.2181 - val_accuracy: 0.9973

24/24 [==============================] - 6s 128ms/step - loss: 0.2284 - accuracy: 0.9921
Error executing job with overrides: []
Traceback (most recent call last):
  File "D:\MLOps\FMClassifier\train.py", line 47, in main
    wandb.log({"loss": loss},{"accuracy": accuracy})
  File "C:\Users\phant\.virtualenvs\MLOps-he8T28m9\lib\site-packages\wandb\sdk\wandb_run.py", line 1213, in log
    if self.history._step > step:
TypeError: '>' not supported between instances of 'int' and 'dict'
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.